-- Seed 500 Curated Cambridge B1 Vocabulary Items
INSERT INTO vocabularies (id, word, pos, ipa, meaning, example, category) VALUES
  ('b1_001', 'abroad', 'adv.', '/əˈbrɔːd/', 'ในต่างประเทศ', 'Studying abroad allows you to learn about diverse global cultures.', 'Travel & Transport'),
  ('b1_002', 'accept', 'v.', '/əkˈsept/', 'ยอมรับ', 'She happily accepted the university''s admission offer.', 'General'),
  ('b1_003', 'accommodation', 'n.', '/əˌkɒməˈdeɪʃn/', 'ที่พักอาศัย, โรงแรม', 'The package tour includes luxury beachfront hotel accommodation.', 'Travel & Transport'),
  ('b1_004', 'accurate', 'adj.', '/ˈækjərət/', 'แม่นยำ, ถูกต้อง', 'The digital thermometer provides extremely accurate body temperature readings.', 'Descriptive Words'),
  ('b1_005', 'achieve', 'v.', '/əˈtʃiːv/', 'บรรลุเป้าหมาย, ทำสำเร็จ', 'She worked tirelessly to achieve her academic goals.', 'Daily Life'),
  ('b1_006', 'acquaintance', 'n.', '/əˈkweɪntəns/', 'คนรู้จัก (แต่ไม่สนิท)', 'He is not a close friend, just an acquaintance from tennis club.', 'Relationships'),
  ('b1_007', 'act', 'v.', '/ækt/', 'กระทำ, แสดง', 'You must act swiftly during emergencies.', 'General'),
  ('b1_008', 'acting', 'n.', '/ˈæktɪŋ/', 'การแสดงละคร/ภาพยนตร์', 'She studied classical acting at a drama academy in London.', 'Arts & Leisure'),
  ('b1_009', 'add', 'v.', '/æd/', 'เพิ่ม, บวก', 'Add a pinch of salt to balance the flavor.', 'General'),
  ('b1_010', 'address', 'v.', '/əˈdres/', 'จัดการปัญหา, จ่าหน้าซอง', 'The government needs to address the affordable housing crisis.', 'General'),
  ('b1_011', 'adequate', 'adj.', '/ˈædɪkwət/', 'เพียงพอ, เหมาะสม', 'Make sure you drink an adequate amount of water during hot summer days.', 'Descriptive Words'),
  ('b1_012', 'adjust', 'v.', '/əˈdʒʌst/', 'ปรับแต่ง', 'Adjust your chair height to avoid back pain.', 'General'),
  ('b1_013', 'admire', 'v.', '/ədˈmaɪər/', 'ชื่นชม, ยกย่อง', 'I really admire her courage to speak in public.', 'Daily Life'),
  ('b1_014', 'admit', 'v.', '/ədˈmɪt/', 'ยอมรับความจริง', 'He finally admitted that he was wrong about the directions.', 'Verbs & Expressions'),
  ('b1_015', 'adopt', 'v.', '/əˈdɒpt/', 'รับเลี้ยงเป็นบุตรบุญธรรม/สัตว์เลี้ยง', 'They decided to adopt a rescue dog from the local animal shelter.', 'Relationships'),
  ('b1_016', 'adventure', 'n.', '/ədˈventʃər/', 'การผจญภัย', 'Their rafting trip down the river was an unforgettable adventure.', 'Arts & Leisure'),
  ('b1_017', 'advise', 'v.', '/ədˈvaɪz/', 'ให้คำแนะนำ', 'Financial experts advise saving at least twenty percent of your income.', 'Verbs & Expressions'),
  ('b1_018', 'affect', 'v.', '/əˈfekt/', 'ส่งผลกระทบต่อ', 'Extreme weather can seriously affect public transport.', 'Daily Life'),
  ('b1_019', 'afford', 'v.', '/əˈfɔːd/', 'มีเงิน/เวลาพอที่จะซื้อหรือทำ', 'We cannot afford to go on an overseas holiday this year.', 'Daily Life'),
  ('b1_020', 'affordable', 'adj.', '/əˈfɔːdəbl/', 'ราคาจับต้องได้, ไม่แพง', 'The district has plenty of clean, affordable student accommodation apartments.', 'Shopping & City'),
  ('b1_021', 'agree', 'v.', '/əˈɡriː/', 'เห็นพ้องต้องกัน', 'We all agreed on the proposed holiday destination.', 'General'),
  ('b1_022', 'aim', 'v.', '/eɪm/', 'ตั้งเป้าหมาย', 'We aim to complete the application by tomorrow morning.', 'General'),
  ('b1_023', 'airline', 'n.', '/ˈeəlaɪn/', 'สายการบิน', 'Which airline offers the best direct flights to Tokyo?', 'Travel & Transport'),
  ('b1_024', 'allergy', 'n.', '/ˈælədʒi/', 'อาการแพ้', 'Always inform the restaurant waiter if you have a severe peanut allergy.', 'Health & Food'),
  ('b1_025', 'allow', 'v.', '/əˈlaʊ/', 'อนุญาตให้ทำ', 'Passengers are not allowed to smoke anywhere inside the terminal.', 'Verbs & Expressions'),
  ('b1_026', 'analyse', 'v.', '/ˈænəlaɪz/', 'วิเคราะห์', 'Scientists analysed the water samples for microplastics.', 'General'),
  ('b1_027', 'ancestor', 'n.', '/ˈænsestər/', 'บรรพบุรุษ', 'Her ancestors migrated from northern Scotland over two centuries ago.', 'Relationships'),
  ('b1_028', 'ancient', 'adj.', '/ˈeɪnʃənt/', 'โบราณ, เก่าแก่มาก', 'Tourists queued to explore the ancient ruins of the Roman Colosseum.', 'Descriptive Words'),
  ('b1_029', 'announce', 'v.', '/əˈnaʊns/', 'ประกาศ', 'The headmaster will announce the winner of the essay contest.', 'General'),
  ('b1_030', 'announcement', 'n.', '/əˈnaʊnsmənt/', 'การประกาศแจ้งข้อมูล', 'Listen carefully to the platform announcement for train updates.', 'Travel & Transport'),
  ('b1_031', 'annoy', 'v.', '/əˈnɔɪ/', 'ทำให้รำคาญใจ', 'Loud notifications during lectures annoy the professor.', 'General'),
  ('b1_032', 'anxious', 'adj.', '/ˈæŋkʃəs/', 'วิตกกังวล, กระวนกระวาย', 'She felt slightly anxious before walking onto the exam stage.', 'Emotions & Traits'),
  ('b1_033', 'apologise', 'v.', '/əˈpɒlədʒaɪz/', 'ขอโทษ', 'He sent a message to apologise for missing the meeting.', 'Daily Life'),
  ('b1_034', 'appetite', 'n.', '/ˈæpɪtaɪt/', 'ความอยากอาหาร', 'A brisk morning jog will surely stimulate your healthy breakfast appetite.', 'Health & Food'),
  ('b1_035', 'applicant', 'n.', '/ˈæplɪkənt/', 'ผู้สมัครงาน', 'Over two hundred applicants applied for the marketing manager position.', 'Work & Career'),
  ('b1_036', 'application', 'n.', '/ˌæplɪˈkeɪʃn/', 'แอปพลิเคชัน, โปรแกรม', 'This vocabulary application helps English learners remember words faster.', 'Education & Tech'),
  ('b1_037', 'apply', 'v.', '/əˈplaɪ/', 'สมัคร, ประยุกต์ใช้', 'She applied for an international scholarship in Melbourne.', 'General'),
  ('b1_038', 'appoint', 'v.', '/əˈpɔɪnt/', 'แต่งตั้ง', 'The board appointed a new executive director.', 'General'),
  ('b1_039', 'appreciate', 'v.', '/əˈpriːʃieɪt/', 'ซาบซึ้ง, เห็นคุณค่า', 'I truly appreciate your thoughtful assistance with my project.', 'General'),
  ('b1_040', 'approach', 'v.', '/əˈprəʊtʃ/', 'เข้าใกล้', 'Slow down as your car approaches the pedestrian crossing.', 'General'),
  ('b1_041', 'approve', 'v.', '/əˈpruːv/', 'อนุมัติ, เห็นชอบ', 'The city council approved plans to build a new public library.', 'General'),
  ('b1_042', 'approximate', 'adj.', '/əˈprɒksɪmət/', 'โดยประมาณ, คร่าวๆ', 'The approximate flight time from London to Bangkok is eleven hours.', 'Descriptive Words'),
  ('b1_043', 'argue', 'v.', '/ˈɑːɡjuː/', 'โต้เถียง, ทะเลาะ', 'They often argue about minor things, but they always make up quickly.', 'Verbs & Expressions'),
  ('b1_044', 'arrange', 'v.', '/əˈreɪndʒ/', 'จัดเตรียม, นัดหมาย', 'Could you arrange a convenient time for us to meet?', 'Daily Life'),
  ('b1_045', 'arrest', 'v.', '/əˈrest/', 'จับกุม', 'The police arrested the suspect near the train station.', 'General'),
  ('b1_046', 'arrive', 'v.', '/əˈraɪv/', 'มาถึง', 'The express train will arrive at platform two momentarily.', 'General'),
  ('b1_047', 'artificial', 'adj.', '/ˌɑːtɪˈfɪʃl/', 'เทียม, ประดิษฐ์ขึ้น', 'This flower arrangement is made of high quality artificial silk.', 'Descriptive Words'),
  ('b1_048', 'assignment', 'n.', '/əˈsaɪnmənt/', 'งานที่ได้รับมอบหมาย, การบ้าน', 'The literature professor gave us a five-page essay assignment.', 'Education & Tech'),
  ('b1_049', 'assist', 'v.', '/əˈsɪst/', 'ช่วยเหลือ', 'Volunteers assisted elderly residents with their weekly groceries.', 'General'),
  ('b1_050', 'assume', 'v.', '/əˈsjuːm/', 'สันนิษฐาน', 'Never assume you know someone''s motives without asking.', 'General'),
  ('b1_051', 'atmosphere', 'n.', '/ˈætməsfɪər/', 'บรรยากาศ', 'The cafe has a warm, relaxed atmosphere that is ideal for afternoon reading.', 'Environment & Nature'),
  ('b1_052', 'attach', 'v.', '/əˈtætʃ/', 'แนบไฟล์, ติดแน่น', 'Attach a recent passport photo to your visa application form.', 'General'),
  ('b1_053', 'attachment', 'n.', '/əˈtætʃmənt/', 'ไฟล์แนบในอีเมล', 'Please review the updated price proposal in the email attachment.', 'Education & Tech'),
  ('b1_054', 'attack', 'v.', '/əˈtæk/', 'โจมตี', 'Cybercriminals attack unsecured networks to steal private credentials.', 'General'),
  ('b1_055', 'attempt', 'v.', '/əˈtempt/', 'พยายามทำ', 'He made a brave attempt to swim across the cold lake.', 'Verbs & Expressions'),
  ('b1_056', 'attend', 'v.', '/əˈtend/', 'เข้าร่วม', 'Hundreds of delegates attended the international climate conference.', 'General'),
  ('b1_057', 'attract', 'v.', '/əˈtrækt/', 'ดึงดูดความสนใจ', 'The summer festival attracts thousands of international visitors.', 'Daily Life'),
  ('b1_058', 'audience', 'n.', '/ˈɔːdiəns/', 'ผู้ชม, ผู้ฟัง', 'The audience burst into enthusiastic applause after the concert.', 'Arts & Leisure'),
  ('b1_059', 'author', 'n.', '/ˈɔːθər/', 'นักเขียน, ผู้แต่ง', 'The author signed copies of her new mystery novel for fans.', 'Arts & Leisure'),
  ('b1_060', 'automatic', 'adj.', '/ˌɔːtəˈmætɪk/', 'อัตโนมัติ', 'The sliding glass doors are automatic and open as you approach.', 'Descriptive Words'),
  ('b1_061', 'avoid', 'v.', '/əˈvɔɪd/', 'หลีกเลี่ยง', 'You should take the highway to avoid morning traffic jams.', 'Daily Life'),
  ('b1_062', 'awkward', 'adj.', '/ˈɔːkwəd/', 'เก้งก้าง, อึดอัดใจ', 'There was an awkward silence when nobody answered the professor''s question.', 'Descriptive Words'),
  ('b1_063', 'baggage', 'n.', '/ˈbæɡɪdʒ/', 'สัมภาระ, กระเป๋าเดินทาง', 'Passengers must collect their checked baggage at carousel number 4.', 'Travel & Transport'),
  ('b1_064', 'bake', 'v.', '/beɪk/', 'อบขนม/อาหาร', 'Grandma baked fresh cinnamon rolls for Sunday breakfast.', 'General'),
  ('b1_065', 'balance', 'v.', '/ˈbæləns/', 'สร้างสมดุล', 'Try to balance challenging study sessions with restful breaks.', 'General'),
  ('b1_066', 'balanced', 'adj.', '/ˈbælənst/', 'สมดุล, ครบถ้วน', 'Nutritionists recommend eating a balanced diet rich in vegetables and whole grains.', 'Health & Food'),
  ('b1_067', 'balcony', 'n.', '/ˈbælkəni/', 'ระเบียง', 'We enjoyed our morning coffee on the sunny balcony overlooking the sea.', 'Home & Living'),
  ('b1_068', 'ballet', 'n.', '/ˈbæleɪ/', 'การแสดงบัลเลต์', 'We purchased front-row tickets to watch Swan Lake at the opera house.', 'Arts & Leisure'),
  ('b1_069', 'ban', 'v.', '/bæn/', 'สั่งห้าม', 'The municipality banned single-use plastic bags in grocery stores.', 'General'),
  ('b1_070', 'band', 'n.', '/bænd/', 'วงดนตรี', 'The indie rock band will perform live at the music festival this weekend.', 'Arts & Leisure'),
  ('b1_071', 'bargain', 'n.', '/ˈbɑːɡən/', 'สินค้าราคาถูกเป็นพิเศษ', 'She found a genuine vintage leather jacket at a real bargain price.', 'Shopping & City'),
  ('b1_072', 'basement', 'n.', '/ˈbeɪsmənt/', 'ชั้นใต้ดิน', 'They converted the damp basement into a modern games and fitness room.', 'Home & Living'),
  ('b1_073', 'battery', 'n.', '/ˈbætəri/', 'แบตเตอรี่', 'The laptop battery lasts for over ten hours on a single charge.', 'Education & Tech'),
  ('b1_074', 'battle', 'v.', '/ˈbætl/', 'ต่อสู้, ฝ่าฟัน', 'Firefighters battled the blaze through the windy night.', 'General'),
  ('b1_075', 'beat', 'v.', '/biːt/', 'เอาชนะ, ตี', 'Our team beat the defending champions by two points.', 'General'),
  ('b1_076', 'beg', 'v.', '/beɡ/', 'ขอร้อง, วิงวอน', 'The child begged his parents for a bedtime story.', 'General'),
  ('b1_077', 'behave', 'v.', '/bɪˈheɪv/', 'ประพฤติตัว, ปฏิบัติตน', 'The pupils were praised for behaving politely during the museum tour.', 'Daily Life'),
  ('b1_078', 'belong', 'v.', '/bɪˈlɒŋ/', 'เป็นของ, สังกัดอยู่', 'Excuse me, does this leather wallet belong to you?', 'Daily Life'),
  ('b1_079', 'belong to', 'phr. v.', '/bɪˈlɒŋ tuː/', 'เป็นของ', 'This vintage fountain pen belongs to my great-grandfather.', 'Verbs & Expressions'),
  ('b1_080', 'bend', 'v.', '/bend/', 'โค้งงอ, ก้ม', 'Bend your knees when lifting heavy luggage to avoid back strain.', 'General'),
  ('b1_081', 'bet', 'v.', '/bet/', 'พนัน, มั่นใจว่า', 'I bet you will pass your Cambridge B1 exam with top marks.', 'General'),
  ('b1_082', 'bilingual', 'adj.', '/ˌbaɪˈlɪŋɡwəl/', 'พูดได้สองภาษา', 'Growing up in Canada allowed her to become effortlessly bilingual in English and French.', 'Descriptive Words'),
  ('b1_083', 'bite', 'v.', '/baɪt/', 'กัด', 'Mosquitoes rarely bite if you apply herbal insect repellent.', 'General'),
  ('b1_084', 'blame', 'v.', '/bleɪm/', 'ตำหนิ, กล่าวโทษ', 'Do not blame others for your own avoidable mistakes.', 'General'),
  ('b1_085', 'blanket', 'n.', '/ˈblæŋkɪt/', 'ผ้าห่ม', 'Wrap yourself in this warm woollen blanket if you feel chilly.', 'Home & Living'),
  ('b1_086', 'bleed', 'v.', '/bliːd/', 'เลือดออก', 'Apply gentle pressure if your finger starts to bleed.', 'General'),
  ('b1_087', 'block', 'v.', '/blɒk/', 'กีดขวาง', 'A fallen branch blocked the narrow country road.', 'General'),
  ('b1_088', 'blow', 'v.', '/bləʊ/', 'พัด, เป่า', 'A gentle sea breeze blew across the sandy beach.', 'General'),
  ('b1_089', 'boarding', 'n.', '/ˈbɔːdɪŋ/', 'การขึ้นเครื่องบิน/เรือ', 'Boarding for flight QR812 will begin at gate 24 in fifteen minutes.', 'Travel & Transport'),
  ('b1_090', 'boil', 'v.', '/bɔɪl/', 'ต้มจนเดือด', 'Boil the water thoroughly before drinking from natural mountain streams.', 'General'),
  ('b1_091', 'boost', 'v.', '/buːst/', 'ส่งเสริม, เพิ่มพูน', 'Flashcard repetition boosts long-term memory significantly.', 'General'),
  ('b1_092', 'borrow', 'v.', '/ˈbɒrəʊ/', 'ขอยืม', 'May I borrow your English dictionary for a moment?', 'Daily Life'),
  ('b1_093', 'bother', 'v.', '/ˈbɒðər/', 'รบกวน, ทำให้กังวล', 'I am very sorry to bother you while you are studying.', 'Daily Life'),
  ('b1_094', 'brake', 'v.', '/breɪk/', 'เหยียบเบรก', 'The bus driver braked quickly to avoid the deer.', 'General'),
  ('b1_095', 'break down', 'phr. v.', '/breɪk daʊn/', 'เครื่องยนต์เสีย, พัง', 'Our family car broke down on the expressway during rush hour.', 'Verbs & Expressions'),
  ('b1_096', 'breathe', 'v.', '/briːð/', 'หายใจ', 'Take deep breaths and stay calm during the timed speaking examination.', 'Health & Food'),
  ('b1_097', 'breed', 'v.', '/briːd/', 'เพาะพันธุ์', 'The conservation park breeds rare sea turtles in safe hatcheries.', 'General'),
  ('b1_098', 'bride', 'n.', '/braɪd/', 'เจ้าสาว', 'The radiant bride wore a breathtaking hand-stitched lace gown.', 'Relationships'),
  ('b1_099', 'brilliant', 'adj.', '/ˈbrɪliənt/', 'ยอดเยี่ยม, ฉลาดหลักแหลม', 'Her brilliant invention solved the clean water crisis for several rural communities.', 'Descriptive Words'),
  ('b1_100', 'bring up', 'phr. v.', '/brɪŋ ʌp/', 'เลี้ยงดูเด็ก, หยิบยกเรื่องขึ้นมา', 'She was lovingly brought up by her grandparents in a rural village.', 'Verbs & Expressions'),
  ('b1_101', 'broadcast', 'v.', '/ˈbrɔːdkɑːst/', 'แพร่ภาพ, ถ่ายทอดสด', 'The national television channel will broadcast the World Cup final live.', 'Media & Society'),
  ('b1_102', 'brochure', 'n.', '/ˈbrəʊʃər/', 'แผ่นพับข้อมูลนำเที่ยว', 'We picked up a colourful travel brochure at the visitor tourist centre.', 'Travel & Transport'),
  ('b1_103', 'browser', 'n.', '/ˈbraʊzər/', 'เว็บเบราว์เซอร์', 'Make sure your internet browser is updated to the latest security version.', 'Education & Tech'),
  ('b1_104', 'brush', 'v.', '/brʌʃ/', 'แปรง', 'Brush your teeth twice a day with fluoride toothpaste.', 'General'),
  ('b1_105', 'burn', 'v.', '/bɜːn/', 'เผาไหม้', 'Campers must ensure campfire embers do not burn unattended.', 'General'),
  ('b1_106', 'burst', 'v.', '/bɜːst/', 'ระเบิดออก, แตกออก', 'The colourful party balloon burst when it touched the cactus.', 'General'),
  ('b1_107', 'bury', 'v.', '/ˈberi/', 'ฝังดิน', 'The dog buried its favourite bone in the backyard garden.', 'General'),
  ('b1_108', 'calculate', 'v.', '/ˈkælkjuleɪt/', 'คำนวณ', 'Use the app''s built-in calculator to calculate your monthly expenses.', 'General'),
  ('b1_109', 'calm', 'v.', '/kɑːm/', 'สงบจิตใจ', 'Listening to soft instrumental music helps calm exam jitters.', 'General'),
  ('b1_110', 'calory', 'n.', '/ˈkæləri/', 'แคลอรี, หน่วยพลังงาน', 'Drinking sweet carbonated drinks adds unnecessary calories to your diet.', 'Health & Food'),
  ('b1_111', 'camp', 'v.', '/kæmp/', 'ตั้งแคมป์', 'We plan to camp near the national forest lake this weekend.', 'General'),
  ('b1_112', 'cancel', 'v.', '/ˈkænsl/', 'ยกเลิก', 'They had to cancel the outdoor festival due to torrential downpours.', 'General'),
  ('b1_113', 'cancelled', 'adj.', '/ˈkænsld/', 'ถูกยกเลิก', 'Due to thick fog, all morning ferry services have been cancelled.', 'Travel & Transport'),
  ('b1_114', 'canvas', 'n.', '/ˈkænvəs/', 'ผ้าใบวาดรูป', 'The painter applied vibrant oil colours onto the blank canvas.', 'Arts & Leisure'),
  ('b1_115', 'capture', 'v.', '/ˈkæptʃər/', 'จับกุม, บันทึกภาพ', 'The camera captured the stunning colors of the sunset.', 'General'),
  ('b1_116', 'care', 'v.', '/keər/', 'ใส่ใจ, ดูแล', 'Good doctors care deeply about their patients'' physical and mental wellbeing.', 'General'),
  ('b1_117', 'career', 'n.', '/kəˈrɪər/', 'อาชีพการงาน, เส้นทางอาชีพ', 'She pursued a successful career in international finance.', 'Work & Career'),
  ('b1_118', 'carpet', 'n.', '/ˈkɑːpɪt/', 'พรมปูพื้น', 'Remember to take off your outdoor shoes before walking on the carpet.', 'Home & Living'),
  ('b1_119', 'carry on', 'phr. v.', '/ˈkæri ɒn/', 'ทำต่อไป, ดำเนินต่อไป', 'Please carry on with your reading while I write on the board.', 'Verbs & Expressions'),
  ('b1_120', 'cashier', 'n.', '/kæˈʃɪər/', 'พนักงานคิดเงิน, แคชเชียร์', 'Hand your store discount coupon to the cashier before paying for your groceries.', 'Shopping & City'),
  ('b1_121', 'catch up', 'phr. v.', '/kætʃ ʌp/', 'ตามทัน, พบปะพูดคุยอัปเดต', 'Let us grab coffee this weekend to catch up on each other''s news.', 'Verbs & Expressions'),
  ('b1_122', 'cautious', 'adj.', '/ˈkɔːʃəs/', 'ระมัดระวัง, รอบคอบ', 'Drivers should be especially cautious on wet, slippery roads.', 'Descriptive Words'),
  ('b1_123', 'ceiling', 'n.', '/ˈsiːlɪŋ/', 'เพดาน', 'The high ceiling makes the living room feel spacious and airy.', 'Home & Living'),
  ('b1_124', 'celebrate', 'v.', '/ˈselɪbreɪt/', 'เฉลิมฉลอง', 'The team gathered at the restaurant to celebrate their championship.', 'Daily Life'),
  ('b1_125', 'celebrity', 'n.', '/səˈlebrəti/', 'คนมีชื่อเสียง, ดารา', 'The famous Hollywood celebrity attended the charity fundraising gala.', 'Media & Society'),
  ('b1_126', 'certificate', 'n.', '/səˈtɪfɪkət/', 'ประกาศนียบัตร', 'Students who complete the intensive course will receive an official certificate.', 'Education & Tech'),
  ('b1_127', 'challenge', 'v.', '/ˈtʃælɪndʒ/', 'ท้าทาย', 'This advanced quiz challenges your grammar comprehension.', 'General'),
  ('b1_128', 'charge', 'v.', '/tʃɑːdʒ/', 'คิดราคา, ชาร์จแบต', 'Remember to charge your smartphone battery before leaving home.', 'General'),
  ('b1_129', 'chase', 'v.', '/tʃeɪs/', 'ไล่ตาม', 'The playful kitten chased a stray red wool ball across the floor.', 'General'),
  ('b1_130', 'chat', 'v.', '/tʃæt/', 'สนทนา', 'We sat in the cafe and chatted happily for several hours.', 'General'),
  ('b1_131', 'cheat', 'v.', '/tʃiːt/', 'โกง', 'Honest students never cheat during examinations.', 'General'),
  ('b1_132', 'check in', 'phr. v.', '/tʃek ɪn/', 'เช็คอิน (ที่พัก/สนามบิน)', 'We must check in at the international airport two hours before departure.', 'Verbs & Expressions'),
  ('b1_133', 'check out', 'phr. v.', '/tʃek aʊt/', 'เช็คเอาท์, ตรวจสอบดู', 'Hotel guests must check out before noon on their departure date.', 'Verbs & Expressions'),
  ('b1_134', 'cheer', 'v.', '/tʃɪər/', 'ส่งเสียงเชียร์', 'The fans cheered wildly when their striker scored the winning goal.', 'General'),
  ('b1_135', 'cheerful', 'adj.', '/ˈtʃɪəfl/', 'ร่าเริงแจ่มใส', 'His cheerful personality always lifts the mood of the entire office.', 'Descriptive Words'),
  ('b1_136', 'childhood', 'n.', '/ˈtʃaɪldhʊd/', 'วัยเด็ก', 'He spent his joyful childhood exploring the countryside with his cousins.', 'Relationships'),
  ('b1_137', 'chimney', 'n.', '/ˈtʃɪmni/', 'ปล่องไฟ', 'White smoke drifted gently from the brick chimney on the cottage roof.', 'Home & Living'),
  ('b1_138', 'choose', 'v.', '/tʃuːz/', 'เลือกสรร', 'Choose healthy snacks like almonds and fresh berries over candy.', 'General'),
  ('b1_139', 'cinema', 'n.', '/ˈsɪnəmə/', 'โรงภาพยนตร์', 'Let us meet outside the cinema twenty minutes before the film starts.', 'Arts & Leisure'),
  ('b1_140', 'citizen', 'n.', '/ˈsɪtɪzn/', 'พลเมือง, ประชาชน', 'Every responsible citizen should participate in the upcoming local council election.', 'Media & Society'),
  ('b1_141', 'claim', 'v.', '/kleɪm/', 'อ้างสิทธิ์', 'You can claim compensation if your flight is delayed by over four hours.', 'General'),
  ('b1_142', 'clap', 'v.', '/klæp/', 'ปรบมือ', 'The whole hall clapped enthusiastically after the graduation speech.', 'General'),
  ('b1_143', 'clarify', 'v.', '/ˈklærəfaɪ/', 'ทำให้ชัดเจน', 'Could you clarify the final question on the assignment sheet?', 'General'),
  ('b1_144', 'climate', 'n.', '/ˈklaɪmət/', 'สภาพภูมิอากาศ', 'Global climate change is causing polar ice caps to melt at alarming rates.', 'Environment & Nature'),
  ('b1_145', 'climb', 'v.', '/klaɪm/', 'ปีนป่าย', 'They climbed to the peak of the mountain before midday.', 'General'),
  ('b1_146', 'colleague', 'n.', '/ˈkɒliːɡ/', 'เพื่อนร่วมงาน', 'I usually have lunch with my colleagues at the company cafeteria.', 'Work & Career'),
  ('b1_147', 'collect', 'v.', '/kəˈlekt/', 'สะสม, เก็บรวม', 'She collects vintage postage stamps from European countries.', 'General'),
  ('b1_148', 'combine', 'v.', '/kəmˈbaɪn/', 'ผสมผสาน', 'Combine flour, eggs, and milk until the batter is smooth.', 'General'),
  ('b1_149', 'come across', 'phr. v.', '/kʌm əˈkrɒs/', 'พบเจอโดยบังเอิญ', 'I came across an old family photo album while cleaning the attic.', 'Verbs & Expressions'),
  ('b1_150', 'comedy', 'n.', '/ˈkɒmədi/', 'ภาพยนตร์หรือละครตลก', 'Watching a lighthearted comedy is a great way to relieve stress.', 'Arts & Leisure'),
  ('b1_151', 'comfort', 'v.', '/ˈkʌmfət/', 'ปลอบประโลม', 'The mother gently comforted her crying baby with a soft lullaby.', 'General'),
  ('b1_152', 'command', 'v.', '/kəˈmɑːnd/', 'สั่งการ', 'The captain commanded the ship''s crew to prepare the lifeboats.', 'General'),
  ('b1_153', 'communicate', 'v.', '/kəˈmjuːnɪkeɪt/', 'สื่อสาร', 'Effective teams communicate clearly and listen empathetically.', 'General'),
  ('b1_154', 'community', 'n.', '/kəˈmjuːnəti/', 'ชุมชน', 'Local residents gathered at the community centre to discuss playground renovations.', 'Media & Society'),
  ('b1_155', 'commute', 'v.', '/kəˈmjuːt/', 'เดินทางไปกลับที่ทำงาน', 'Many office workers commute by rapid transit train every weekday.', 'Travel & Transport'),
  ('b1_156', 'compete', 'v.', '/kəmˈpiːt/', 'แข่งขัน', 'Athletes from eighty nations compete in the international tournament.', 'General'),
  ('b1_157', 'complain', 'v.', '/kəmˈpleɪn/', 'ร้องเรียน, บ่น', 'Customers have the right to complain if the service is substandard.', 'Daily Life'),
  ('b1_158', 'complaint', 'n.', '/kəmˈpleɪnt/', 'ข้อร้องเรียน', 'The store manager promptly resolved the customer''s complaint with a replacement.', 'Shopping & City'),
  ('b1_159', 'complete', 'v.', '/kəmˈpliːt/', 'ทำเสร็จสมบูรณ์', 'Please complete all registration fields before submitting the online form.', 'General'),
  ('b1_160', 'concentrate', 'v.', '/ˈkɒnsntreɪt/', 'มีสมาธิตั้งใจ', 'Turn off phone notifications so you can concentrate on your reading.', 'General'),
  ('b1_161', 'concert', 'n.', '/ˈkɒnsət/', 'คอนเสิร์ต', 'Thousands of enthusiastic fans attended the outdoor rock concert.', 'Arts & Leisure'),
  ('b1_162', 'conclude', 'v.', '/kənˈkluːd/', 'สรุป', 'The keynote speaker concluded her lecture with an inspirational quote.', 'General'),
  ('b1_163', 'conduct', 'v.', '/kənˈdʌkt/', 'ดำเนินการ, จัดทำ', 'The university conducts clinical trials under strict international guidelines.', 'General'),
  ('b1_164', 'confess', 'v.', '/kənˈfes/', 'สารภาพ', 'He confessed his nervousness about delivering the commencement address.', 'General'),
  ('b1_165', 'confident', 'adj.', '/ˈkɒnfɪdənt/', 'มั่นใจในตนเอง', 'Practicing speaking aloud will make you feel confident during the test.', 'Emotions & Traits'),
  ('b1_166', 'confirm', 'v.', '/kənˈfɜːm/', 'ยืนยัน', 'Please confirm your hotel reservation by email before Friday.', 'Daily Life'),
  ('b1_167', 'confused', 'adj.', '/kənˈfjuːzd/', 'สับสน, งงงวย', 'The ambiguous road signage left many foreign drivers completely confused.', 'Emotions & Traits'),
  ('b1_168', 'congratulate', 'v.', '/kənˈɡrætʃuleɪt/', 'แสดงความยินดี', 'I want to congratulate you on achieving your B1 certificate.', 'General'),
  ('b1_169', 'connect', 'v.', '/kəˈnekt/', 'เชื่อมต่อ', 'The app automatically connects with Supabase to sync your study progress.', 'General'),
  ('b1_170', 'conquer', 'v.', '/ˈkɒŋkər/', 'พิชิต, เอาชนะ', 'Practice and persistence help you conquer vocabulary anxiety.', 'General'),
  ('b1_171', 'consent', 'v.', '/kənˈsent/', 'ยินยอม', 'Patients must consent in writing before undergoing elective surgery.', 'General'),
  ('b1_172', 'conservation', 'n.', '/ˌkɒnsəˈveɪʃn/', 'การอนุรักษ์ธรรมชาติ', 'Wildlife conservation efforts have helped bring endangered pandas back from extinction.', 'Environment & Nature'),
  ('b1_173', 'consider', 'v.', '/kənˈsɪdər/', 'พิจารณา, คำนึงถึง', 'You must consider all safety rules before operating the equipment.', 'Daily Life'),
  ('b1_174', 'consist', 'v.', '/kənˈsɪst/', 'ประกอบด้วย', 'A balanced breakfast consists of protein, fiber, and clean water.', 'General'),
  ('b1_175', 'construct', 'v.', '/kənˈstrʌkt/', 'ก่อสร้าง', 'Engineers constructed a flood barrier to safeguard the riverside village.', 'General'),
  ('b1_176', 'consume', 'v.', '/kənˈsjuːm/', 'บริโภค', 'Athletes consume complex carbohydrates before competing in marathons.', 'General'),
  ('b1_177', 'consumer', 'n.', '/kənˈsjuːmər/', 'ผู้บริโภค', 'Modern consumers increasingly prefer shopping via trusted smartphone apps.', 'Shopping & City'),
  ('b1_178', 'contact', 'v.', '/ˈkɒntækt/', 'ติดต่อสื่อสาร', 'Feel free to contact customer support if you experience any login issues.', 'General'),
  ('b1_179', 'contain', 'v.', '/kənˈteɪn/', 'บรรจุ, มีส่วนประกอบของ', 'This bottle contains a concentrated herbal extract.', 'Daily Life'),
  ('b1_180', 'continue', 'v.', '/kənˈtɪnjuː/', 'ดำเนินการต่อ', 'Continue practicing your flashcards daily to maintain your study streak.', 'General'),
  ('b1_181', 'contract', 'n.', '/ˈkɒntrækt/', 'สัญญาจ้าง, ข้อตกลงทางกฎหมาย', 'Read the terms carefully before signing the employment contract.', 'Work & Career'),
  ('b1_182', 'contribute', 'v.', '/kənˈtrɪbjuːt/', 'มีส่วนร่วม, บริจาค', 'Local businesses contributed funds to rebuild the neighborhood community park.', 'General'),
  ('b1_183', 'control', 'v.', '/kənˈtrəʊl/', 'ควบคุม', 'Smart thermostats let homeowners control temperature from their mobile phones.', 'General'),
  ('b1_184', 'convenient', 'adj.', '/kənˈviːniənt/', 'สะดวกสบาย', 'Living near the underground station is remarkably convenient for commuting.', 'Descriptive Words'),
  ('b1_185', 'convert', 'v.', '/kənˈvɜːt/', 'แปลงสภาพ', 'Solar cells convert sunlight directly into usable electrical power.', 'General'),
  ('b1_186', 'convince', 'v.', '/kənˈvɪns/', 'โน้มน้าวใจ, ทำให้เชื่อ', 'Her well-researched presentation convinced everyone in the room.', 'Daily Life'),
  ('b1_187', 'cook', 'v.', '/kʊk/', 'ปรุงอาหาร', 'Learn to cook nutritious meals at home to save money and stay fit.', 'General'),
  ('b1_188', 'cope', 'v.', '/kəʊp/', 'รับมือไหว', 'Deep breathing exercises help students cope with exam pressure.', 'General'),
  ('b1_189', 'correct', 'v.', '/kəˈrekt/', 'แก้ไขให้ถูกต้อง', 'The teacher gently corrected my pronunciation during speaking practice.', 'General'),
  ('b1_190', 'corridor', 'n.', '/ˈkɒrɪdɔːr/', 'ทางเดินในอาคาร', 'Walk down the long corridor and take the second door on your right.', 'Home & Living'),
  ('b1_191', 'cost', 'v.', '/kɒst/', 'มีราคา', 'Good quality running shoes cost between fifty and one hundred pounds.', 'General'),
  ('b1_192', 'costume', 'n.', '/ˈkɒstjuːm/', 'เครื่องแต่งกายการแสดง', 'The historical drama won an international award for best costume design.', 'Arts & Leisure'),
  ('b1_193', 'cottage', 'n.', '/ˈkɒtɪdʒ/', 'กระท่อม, บ้านพักตากอากาศ', 'They spent a peaceful autumn weekend at a cosy countryside cottage.', 'Home & Living'),
  ('b1_194', 'cough', 'v.', '/kɒf/', 'ไอ', 'Cover your mouth when you cough to prevent spreading germs.', 'General'),
  ('b1_195', 'count', 'v.', '/kaʊnt/', 'นับจำนวน', 'Count the total number of mastered words in your study dashboard.', 'General'),
  ('b1_196', 'count on', 'phr. v.', '/kaʊnt ɒn/', 'พึ่งพาได้, ไว้วางใจ', 'You can always count on David whenever you need reliable help.', 'Verbs & Expressions'),
  ('b1_197', 'couple', 'n.', '/ˈkʌpl/', 'คู่รัก, สามีภรรยา', 'The newlywed couple spent their sunny honeymoon touring Italy.', 'Relationships'),
  ('b1_198', 'course', 'n.', '/kɔːs/', 'หลักสูตร, คอร์สเรียน', 'I signed up for an advanced online web development course.', 'Education & Tech'),
  ('b1_199', 'crash', 'v.', '/kræʃ/', 'ชน, ชนเสียหาย', 'Fortunately, no one was injured when the delivery drone crashed in the field.', 'General'),
  ('b1_200', 'create', 'v.', '/kriˈeɪt/', 'สร้างสรรค์', 'Interactive quizzes create engaging learning experiences for students.', 'General'),
  ('b1_201', 'criticize', 'v.', '/ˈkrɪtɪsaɪz/', 'วิพากษ์วิจารณ์', 'Constructive feedback aims to guide learners rather than criticize them harshly.', 'General'),
  ('b1_202', 'cross', 'v.', '/krɒs/', 'ข้าม', 'Always check both directions before you cross the busy street.', 'General'),
  ('b1_203', 'crowded', 'adj.', '/ˈkraʊdɪd/', 'แออัด, หนาแน่นไปด้วยผู้คน', 'The night market is always crowded on Friday evenings.', 'Descriptive Words'),
  ('b1_204', 'crucial', 'adj.', '/ˈkruːʃl/', 'สำคัญยิ่งยวด, ชี้ขาด', 'Regular practice is crucial if you want to achieve B1 mastery.', 'Descriptive Words'),
  ('b1_205', 'cry', 'v.', '/kraɪ/', 'ร้องไห้', 'Tears of joy were shed when the rescue team found the lost hikers.', 'General'),
  ('b1_206', 'culture', 'n.', '/ˈkʌltʃər/', 'วัฒนธรรม', 'Experiencing traditional cuisine is a delightful way to understand foreign culture.', 'Media & Society'),
  ('b1_207', 'cure', 'v.', '/kjʊər/', 'รักษาให้หายขาด', 'Doctors are working hard to discover medications that can cure rare diseases.', 'Health & Food'),
  ('b1_208', 'curious', 'adj.', '/ˈkjʊəriəs/', 'อยากรู้อยากเห็น, ใฝ่รู้', 'Curious children always ask insightful questions about how nature works.', 'Emotions & Traits'),
  ('b1_209', 'curl', 'v.', '/kɜːl/', 'ม้วนงอ', 'The sleepy cat curled up on the soft armchair cushion.', 'General'),
  ('b1_210', 'currency', 'n.', '/ˈkʌrənsi/', 'สกุลเงิน', 'You can easily exchange major foreign currencies at the airport bank kiosk.', 'Shopping & City'),
  ('b1_211', 'curriculum', 'n.', '/kəˈrɪkjələm/', 'หลักสูตรการเรียนการสอน', 'The modern school curriculum emphasizes science, technology, and coding.', 'Education & Tech'),
  ('b1_212', 'curtain', 'n.', '/ˈkɜːtn/', 'ม่านเวที, ผ้าม่าน', 'The heavy velvet curtain rose as the stage lights illuminated the cast.', 'Arts & Leisure'),
  ('b1_213', 'cushion', 'n.', '/ˈkʊʃn/', 'หมอนอิง', 'The sofa is decorated with colourful embroidered cushions.', 'Home & Living'),
  ('b1_214', 'customs', 'n.', '/ˈkʌstəmz/', 'ด่านศุลกากร', 'You must declare any taxable electronic goods when passing through customs.', 'Travel & Transport'),
  ('b1_215', 'damage', 'n.', '/ˈdæmɪdʒ/', 'ความเสียหาย', 'The storm caused minor roof damage to several coastal village cottages.', 'Environment & Nature'),
  ('b1_216', 'dance', 'v.', '/dɑːns/', 'เต้นรำ', 'Villagers danced joyfully to celebrate the autumn harvest.', 'General'),
  ('b1_217', 'dare', 'v.', '/deər/', 'กล้าที่จะทำ', 'Few climbers dare to ascend the steep icy cliff without ropes.', 'General'),
  ('b1_218', 'database', 'n.', '/ˈdeɪtəbeɪs/', 'ฐานข้อมูล', 'All student progress records are securely stored in the Supabase database.', 'Education & Tech'),
  ('b1_219', 'deadline', 'n.', '/ˈdedlaɪn/', 'กำหนดส่งงาน, เส้นตาย', 'Our team is working late to meet the client''s Friday deadline.', 'Work & Career'),
  ('b1_220', 'deal', 'v.', '/diːl/', 'แจกไพ่, จัดการ', 'Managers must deal fairly with workplace disputes.', 'General'),
  ('b1_221', 'deal with', 'phr. v.', '/diːl wɪð/', 'รับมือกับ, จัดการปัญหา', 'Customer service agents must learn to deal with upset callers calmly.', 'Verbs & Expressions'),
  ('b1_222', 'debate', 'v.', '/dɪˈbeɪt/', 'โต้วาที', 'The candidates debated economic policies on national television.', 'General'),
  ('b1_223', 'decide', 'v.', '/dɪˈsaɪd/', 'ตัดสินใจ', 'They decided to move to a quieter town outside London.', 'Daily Life'),
  ('b1_224', 'declare', 'v.', '/dɪˈkleər/', 'แถลง, ประกาศ', 'Travelers must declare agricultural produce at airport customs.', 'General'),
  ('b1_225', 'decorate', 'v.', '/ˈdekəreɪt/', 'ตกแต่ง', 'They decorated the dining room with paper lanterns and flowers.', 'General'),
  ('b1_226', 'decorating', 'n.', '/ˈdekəreɪtɪŋ/', 'การตกแต่งภายใน', 'They spent their holiday painting and decorating the nursery.', 'Home & Living'),
  ('b1_227', 'decrease', 'v.', '/dɪˈkriːs/', 'ลดลง', 'Daily meditation decreases stress hormones in the body.', 'General'),
  ('b1_228', 'defend', 'v.', '/dɪˈfend/', 'ปกป้อง', 'Lawyers defend their clients'' rights vigorously in court.', 'General'),
  ('b1_229', 'define', 'v.', '/dɪˈfaɪn/', 'นิยามความหมาย', 'Can you define the difference between a noun and an adjective?', 'General'),
  ('b1_230', 'degree', 'n.', '/dɪˈɡriː/', 'ปริญญาบัตร', 'She graduated with high honours, earning a bachelor''s degree in biology.', 'Education & Tech'),
  ('b1_231', 'delay', 'v.', '/dɪˈleɪ/', 'ทำให้ล่าช้า, เลื่อนเวลา', 'Heavy snowfall delayed the departure of flight BA204.', 'Daily Life'),
  ('b1_232', 'delayed', 'adj.', '/dɪˈleɪd/', 'ล่าช้า, ดีเลย์', 'Our express coach was delayed by two hours due to highway maintenance.', 'Travel & Transport'),
  ('b1_233', 'delete', 'v.', '/dɪˈliːt/', 'ลบข้อมูล', 'Be careful not to delete essential system files on your computer.', 'General'),
  ('b1_234', 'delicious', 'adj.', '/dɪˈlɪʃəs/', 'อร่อยมาก', 'The home-cooked Italian pasta was truly delicious and flavourful.', 'Health & Food'),
  ('b1_235', 'delighted', 'adj.', '/dɪˈlaɪtɪd/', 'ยินดีเป็นอย่างยิ่ง, ปลื้มใจ', 'We were delighted to hear that you passed your Cambridge B1 exam with distinction.', 'Emotions & Traits'),
  ('b1_236', 'deliver', 'v.', '/dɪˈlɪvər/', 'จัดส่งสินค้า/พัสดุ', 'The online store promises to deliver all orders within 24 hours.', 'Daily Life'),
  ('b1_237', 'demand', 'v.', '/dɪˈmɑːnd/', 'เรียกร้อง', 'Employees demanded better safety standards in the manufacturing plant.', 'General'),
  ('b1_238', 'demonstrate', 'v.', '/ˈdemənstreɪt/', 'สาธิตให้ดู', 'The chef demonstrated how to chop herbs with culinary precision.', 'General'),
  ('b1_239', 'deny', 'v.', '/dɪˈnaɪ/', 'ปฏิเสธความจริง', 'The suspect denied any involvement in the neighborhood burglary.', 'General'),
  ('b1_240', 'departure', 'n.', '/dɪˈpɑːtʃər/', 'การออกเดินทาง, เที่ยวบินขาออก', 'Check the electronic departures screen to see your flight''s gate number.', 'Travel & Transport'),
  ('b1_241', 'depend', 'v.', '/dɪˈpend/', 'ขึ้นอยู่กับ, พึ่งพา', 'Our weekend plans depend entirely on the weather forecast.', 'Daily Life'),
  ('b1_242', 'depend on', 'phr. v.', '/dɪˈpend ɒn/', 'ขึ้นอยู่กับ', 'Whether we go hiking tomorrow depends on the weather conditions.', 'Verbs & Expressions'),
  ('b1_243', 'deposit', 'v.', '/dɪˈpɒzɪt/', 'ฝากเงิน', 'She deposited her monthly pay check into her high-interest savings account.', 'General'),
  ('b1_244', 'describe', 'v.', '/dɪˈskraɪb/', 'อธิบาย, บรรยายลักษณะ', 'Can you describe the missing person to the police officer?', 'Daily Life'),
  ('b1_245', 'deserve', 'v.', '/dɪˈzɜːv/', 'สมควรได้รับ', 'After months of overtime work, she truly deserves a long holiday.', 'Daily Life'),
  ('b1_246', 'design', 'v.', '/dɪˈzaɪn/', 'ออกแบบ', 'Architects designed an energy-efficient library with natural skylights.', 'General'),
  ('b1_247', 'destination', 'n.', '/ˌdestɪˈneɪʃn/', 'จุดหมายปลายทาง', 'The tropical island is one of Southeast Asia''s top tourist destinations.', 'Travel & Transport'),
  ('b1_248', 'destroy', 'v.', '/dɪˈstrɔɪ/', 'ทำลายล้าง', 'The fierce wildfire destroyed several historic buildings in the valley.', 'Daily Life'),
  ('b1_249', 'detect', 'v.', '/dɪˈtekt/', 'ตรวจพบ', 'Smoke sensors detect early traces of fire in modern office buildings.', 'General'),
  ('b1_250', 'determine', 'v.', '/dɪˈtɜːmɪn/', 'กำหนด, ตัดสินใจแน่วแน่', 'Dedication determines how quickly you master a foreign language.', 'General'),
  ('b1_251', 'develop', 'v.', '/dɪˈveləp/', 'พัฒนา', 'Reading widely develops a rich and expressive vocabulary.', 'General'),
  ('b1_252', 'device', 'n.', '/dɪˈvaɪs/', 'อุปกรณ์อิเล็กทรอนิกส์', 'Modern mobile devices allow people to study anywhere, anytime.', 'Education & Tech'),
  ('b1_253', 'dialogue', 'n.', '/ˈdaɪəlɒɡ/', 'บทสนทนา, การเจรจา', 'Open dialogue between parents and teenagers builds trust and mutual understanding.', 'Media & Society'),
  ('b1_254', 'diet', 'n.', '/ˈdaɪət/', 'อาหารการกิน, การควบคุมอาหาร', 'A Mediterranean diet is well-known for promoting long-term cardiovascular health.', 'Health & Food'),
  ('b1_255', 'differ', 'v.', '/ˈdɪfər/', 'แตกต่าง', 'British English and American English differ slightly in vocabulary and spelling.', 'General'),
  ('b1_256', 'digital', 'adj.', '/ˈdɪdʒɪtl/', 'ดิจิทัล', 'Digital textbooks are much lighter to carry than traditional heavy paper books.', 'Education & Tech'),
  ('b1_257', 'direct', 'v.', '/dəˈrekt/', 'ชี้แนะ, กำกับ', 'Traffic wardens directed vehicles around the flooded intersection.', 'General'),
  ('b1_258', 'disagree', 'v.', '/ˌdɪsəˈɡriː/', 'ไม่เห็นด้วย', 'It is acceptable to disagree with peers as long as discussions remain polite.', 'General'),
  ('b1_259', 'disappear', 'v.', '/ˌdɪsəˈpɪər/', 'หายตัวไป, สาบสูญ', 'The magician made the gold ring disappear in front of our eyes.', 'Daily Life'),
  ('b1_260', 'disappoint', 'v.', '/ˌdɪsəˈpɔɪnt/', 'ทำให้ผิดหวัง', 'The sequel movie did not disappoint passionate fans of the original book.', 'General'),
  ('b1_261', 'disappointed', 'adj.', '/ˌdɪsəˈpɔɪntɪd/', 'ผิดหวัง', 'He was understandably disappointed when the concert was abruptly called off.', 'Emotions & Traits'),
  ('b1_262', 'disaster', 'n.', '/dɪˈzɑːstər/', 'ภัยพิบัติ', 'Volunteers gathered quickly to provide food and clean water after the natural disaster.', 'Environment & Nature'),
  ('b1_263', 'discount', 'n.', '/ˈdɪskaʊnt/', 'ส่วนลด', 'Students and senior citizens receive a twenty percent discount on cinema tickets.', 'Shopping & City'),
  ('b1_264', 'discover', 'v.', '/dɪˈskʌvər/', 'ค้นพบ', 'Scientists discovered an ancient underwater city off the coast.', 'Daily Life'),
  ('b1_265', 'discuss', 'v.', '/dɪˈskʌs/', 'อภิปราย', 'Students gathered in study circles to discuss the historical novel.', 'General'),
  ('b1_266', 'disease', 'n.', '/dɪˈziːz/', 'โรคภัยไข้เจ็บ', 'Washing your hands frequently stops the spread of infectious disease.', 'Health & Food'),
  ('b1_267', 'dislike', 'v.', '/dɪsˈlaɪk/', 'ไม่ชอบ', 'Many young children dislike eating bitter cruciferous vegetables.', 'General'),
  ('b1_268', 'dismiss', 'v.', '/dɪsˈmɪs/', 'ปล่อยเลิก, ยกเลิก', 'The teacher dismissed the class as the afternoon school bell chimed.', 'General'),
  ('b1_269', 'display', 'v.', '/dɪˈspleɪ/', 'จัดแสดง', 'The museum displays rare Egyptian papyrus scrolls behind protective glass.', 'General'),
  ('b1_270', 'distribute', 'v.', '/dɪˈstrɪbjuːt/', 'แจกจ่าย', 'Volunteers distributed warm meals to families affected by the flood.', 'General'),
  ('b1_271', 'disturb', 'v.', '/dɪˈstɜːb/', 'รบกวน', 'Please hang the ''Do Not Disturb'' sign on your hotel room door.', 'General'),
  ('b1_272', 'divide', 'v.', '/dɪˈvaɪd/', 'แบ่งแยก', 'Divide your study time into twenty-five minute focused intervals.', 'General'),
  ('b1_273', 'divorce', 'n.', '/dɪˈvɔːs/', 'การหย่าร้าง', 'They remained respectful friends even after their mutual divorce.', 'Relationships'),
  ('b1_274', 'doubt', 'v.', '/daʊt/', 'สงสัย, เคลือบแคลง', 'Nobody doubts her integrity and dedication to community service.', 'General'),
  ('b1_275', 'download', 'v.', '/ˌdaʊnˈləʊd/', 'ดาวน์โหลดข้อมูล', 'You can download the PDF grammar guide directly to your smartphone.', 'Education & Tech'),
  ('b1_276', 'downstairs', 'adv.', '/ˌdaʊnˈsteəz/', 'ชั้นล่าง', 'My father is working in his study downstairs right now.', 'Home & Living'),
  ('b1_277', 'drag', 'v.', '/dræɡ/', 'ลาก', 'You can drag and drop flashcard items into your custom study list.', 'General'),
  ('b1_278', 'drain', 'v.', '/dreɪn/', 'ระบายน้ำ', 'Drain the cooked pasta thoroughly before stirring in the tomato sauce.', 'General'),
  ('b1_279', 'dramatic', 'adj.', '/drəˈmætɪk/', 'น่าตื่นเต้นเร้าใจ, เปลี่ยนแปลงอย่างเห็นได้ชัด', 'There was a dramatic improvement in her listening exam scores.', 'Descriptive Words'),
  ('b1_280', 'drop out', 'phr. v.', '/drɒp aʊt/', 'ออกกลางคัน, ลาออกจากเรียน', 'He dropped out of university to launch his own software company.', 'Verbs & Expressions'),
  ('b1_281', 'drought', 'n.', '/draʊt/', 'ภัยแล้ง', 'A prolonged severe drought ruined crops and depleted rural water reservoirs.', 'Environment & Nature'),
  ('b1_282', 'drown', 'v.', '/draʊn/', 'จมน้ำ', 'Lifeguards patrol the beach to ensure no swimmers drown in strong rip currents.', 'General'),
  ('b1_283', 'earn', 'v.', '/ɜːn/', 'หาเงินได้, ได้รับจากการทำงาน', 'She earns extra pocket money by tutoring high school algebra on weekends.', 'General'),
  ('b1_284', 'earthquake', 'n.', '/ˈɜːθkweɪk/', 'แผ่นดินไหว', 'Modern skyscrapers in Japan are engineered to withstand powerful earthquakes.', 'Environment & Nature'),
  ('b1_285', 'educate', 'v.', '/ˈedʒukeɪt/', 'ให้การศึกษา', 'Public awareness campaigns educate drivers on bicycle safety distances.', 'General'),
  ('b1_286', 'efficient', 'adj.', '/ɪˈfɪʃnt/', 'มีประสิทธิภาพ, รวดเร็วคุ้มค่า', 'High-speed electric trains are an efficient mode of modern transport.', 'Descriptive Words'),
  ('b1_287', 'elect', 'v.', '/ɪˈlekt/', 'เลือกตั้ง', 'Citizens voted in record numbers to elect the new city mayor.', 'General'),
  ('b1_288', 'eliminate', 'v.', '/ɪˈlɪmɪneɪt/', 'กำจัดให้หมดไป', 'Healthy lifestyle changes eliminate many avoidable cardiovascular risks.', 'General'),
  ('b1_289', 'embarrass', 'v.', '/ɪmˈbærəs/', 'ทำให้อับอาย', 'Try not to embarrass someone when pointing out a slip of the tongue.', 'General'),
  ('b1_290', 'embarrassed', 'adj.', '/ɪmˈbærəst/', 'อับอาย, เก้อเขิน', 'She felt embarrassed when her phone rang loudly inside the quiet study hall.', 'Emotions & Traits'),
  ('b1_291', 'emerge', 'v.', '/ɪˈmɜːdʒ/', 'ปรากฏขึ้นมา', 'The bright sun emerged from behind the mountain mist.', 'General'),
  ('b1_292', 'emphasize', 'v.', '/ˈemfəsaɪz/', 'เน้นย้ำ', 'Cambridge examiners emphasize the importance of fluent, natural communication.', 'General'),
  ('b1_293', 'employ', 'v.', '/ɪmˈplɔɪ/', 'ว่าจ้างงาน', 'The tech company employs over five hundred software engineers in Dublin.', 'General'),
  ('b1_294', 'employee', 'n.', '/ɪmˈplɔɪiː/', 'พนักงาน, ลูกจ้าง', 'The tech company offers flexible working hours to all full-time employees.', 'Work & Career'),
  ('b1_295', 'employer', 'n.', '/ɪmˈplɔɪər/', 'นายจ้าง, ผู้ว่าจ้าง', 'A good employer values employee wellness and professional development.', 'Work & Career'),
  ('b1_296', 'enable', 'v.', '/ɪˈneɪbl/', 'ทำให้สามารถทำได้', 'Interactive learning platforms enable students to study at their own pace.', 'General'),
  ('b1_297', 'encourage', 'v.', '/ɪnˈkʌrɪdʒ/', 'ให้กำลังใจ, สนับสนุน', 'Good teachers always encourage their students to ask creative questions.', 'Daily Life'),
  ('b1_298', 'engagement', 'n.', '/ɪnˈɡeɪdʒmənt/', 'การหมั้นหมาย', 'They announced their engagement at a family dinner gathering.', 'Relationships'),
  ('b1_299', 'entertain', 'v.', '/ˌentəˈteɪn/', 'สร้างความบันเทิง', 'A talented street musician entertained the crowd with his guitar.', 'Daily Life'),
  ('b1_300', 'enthusiastic', 'adj.', '/ɪnˌθjuːziˈæstɪk/', 'กระตือรือร้น, มีไฟ', 'The young volunteers were enthusiastic about planting trees in the city park.', 'Emotions & Traits'),
  ('b1_301', 'environment', 'n.', '/ɪnˈvaɪrənmənt/', 'สิ่งแวดล้อม', 'Planting more urban trees cleans the air and protects the natural environment.', 'Environment & Nature'),
  ('b1_302', 'escape', 'v.', '/ɪˈskeɪp/', 'หลบหนี', 'The clever fox escaped safely into the dense woodland undergrowth.', 'General'),
  ('b1_303', 'essay', 'n.', '/ˈeseɪ/', 'เรียงความ, บทความวิชาการ', 'Write a persuasive essay debating the advantages of renewable energy.', 'Education & Tech'),
  ('b1_304', 'essential', 'adj.', '/ɪˈsenʃl/', 'จำเป็นอย่างยิ่ง, ขาดไม่ได้', 'A valid passport is essential for all international travel bookings.', 'Descriptive Words'),
  ('b1_305', 'estimate', 'v.', '/ˈestɪmeɪt/', 'ประมาณการ', 'Contractors estimate the renovation work will take approximately four weeks.', 'General'),
  ('b1_306', 'evaluate', 'v.', '/ɪˈvæljueɪt/', 'ประเมินผล', 'Teachers evaluate students based on coursework, presentations, and exams.', 'General'),
  ('b1_307', 'examine', 'v.', '/ɪɡˈzæmɪn/', 'ตรวจตรา, สอบสวน', 'The customs inspector examined the luggage carefully for undeclared items.', 'General'),
  ('b1_308', 'exchange', 'v.', '/ɪksˈtʃeɪndʒ/', 'แลกเปลี่ยน', 'Foreign students exchanged cultural traditions during international week.', 'General'),
  ('b1_309', 'excite', 'v.', '/ɪkˈsaɪt/', 'ทำให้ตื่นเต้น', 'The prospect of travelling to Europe excited the young backpackers.', 'General'),
  ('b1_310', 'exclude', 'v.', '/ɪkˈskluːd/', 'กีดกัน, คัดออก', 'The basic hotel room price excludes breakfast buffet and airport transfer.', 'General'),
  ('b1_311', 'excursion', 'n.', '/ɪkˈskɜːʃn/', 'การทัศนศึกษา, เที่ยวระยะสั้น', 'The hotel organizes daily boat excursions to the nearby coral reefs.', 'Travel & Transport'),
  ('b1_312', 'excuse', 'v.', '/ɪkˈskjuːz/', 'ยกโทษให้, ให้อภัย', 'Please excuse my late arrival; my train was delayed by track maintenance.', 'General'),
  ('b1_313', 'exercise', 'n.', '/ˈeksəsaɪz/', 'การออกกำลังกาย', 'Regular aerobic exercise keeps your heart strong and lowers stress levels.', 'Health & Food'),
  ('b1_314', 'exhausted', 'adj.', '/ɪɡˈzɔːstɪd/', 'เหนื่อยล้าจนหมดแรง', 'After hiking twenty kilometres up the mountain, we were completely exhausted.', 'Emotions & Traits'),
  ('b1_315', 'exhibit', 'v.', '/ɪɡˈzɪbɪt/', 'จัดแสดง', 'The local museum exhibits Roman artifacts found in the nearby valley.', 'General'),
  ('b1_316', 'exhibition', 'n.', '/ˌeksɪˈbɪʃn/', 'นิทรรศการ', 'The national gallery is hosting an impressive exhibition of modern art.', 'Arts & Leisure'),
  ('b1_317', 'exist', 'v.', '/ɪɡˈzɪst/', 'มีอยู่จริง', 'Fascinating deep-sea creatures exist under immense underwater pressure.', 'General'),
  ('b1_318', 'expand', 'v.', '/ɪkˈspænd/', 'ขยายตัว', 'The software company plans to expand its offices into Southeast Asia.', 'General'),
  ('b1_319', 'expect', 'v.', '/ɪkˈspekt/', 'คาดหวัง, คาดการณ์', 'We expect the train to arrive at the central platform shortly.', 'Daily Life'),
  ('b1_320', 'expensive', 'adj.', '/ɪkˈspensɪv/', 'ราคาแพง', 'Imported sports cars are too expensive for the average working household.', 'Shopping & City'),
  ('b1_321', 'experience', 'n.', '/ɪkˈspɪəriəns/', 'ประสบการณ์การทำงาน', 'The position requires at least three years of graphic design experience.', 'Work & Career'),
  ('b1_322', 'explain', 'v.', '/ɪkˈspleɪn/', 'อธิบาย', 'The coach patiently explained the new defensive strategy.', 'Daily Life'),
  ('b1_323', 'explode', 'v.', '/ɪkˈspləʊd/', 'ระเบิดออก', 'Fireworks exploded across the midnight sky in a dazzling display of light.', 'General'),
  ('b1_324', 'explore', 'v.', '/ɪkˈsplɔːr/', 'สำรวจ', 'Tourists enjoy exploring historic cobblestone streets in ancient European towns.', 'General'),
  ('b1_325', 'express', 'v.', '/ɪkˈspres/', 'แสดงออก', 'Art allows individuals to express deep emotions that words cannot convey.', 'General'),
  ('b1_326', 'extend', 'v.', '/ɪkˈstend/', 'ขยายระยะเวลา/พื้นที่', 'The university library extended its opening hours during final exam week.', 'General'),
  ('b1_327', 'face', 'v.', '/feɪs/', 'เผชิญหน้า', 'Learners must face challenges with patience and consistent daily effort.', 'General'),
  ('b1_328', 'fail', 'v.', '/feɪl/', 'ล้มเหลว, สอบตก', 'Mistakes are not permanent; you only fail when you stop trying.', 'General'),
  ('b1_329', 'fare', 'n.', '/feər/', 'ค่าโดยสาร', 'The bus fare has slightly increased because of rising fuel prices.', 'Travel & Transport'),
  ('b1_330', 'fasten', 'v.', '/ˈfɑːsn/', 'รัดให้แน่น', 'Please fasten your seat belt securely while the aircraft is taxiing.', 'General'),
  ('b1_331', 'feature', 'v.', '/ˈfiːtʃər/', 'มีจุดเด่นเป็น', 'The new smartphone model features an ultra-sharp high-definition camera.', 'General'),
  ('b1_332', 'feed', 'v.', '/fiːd/', 'ให้อาหาร', 'Visitors are reminded not to feed the wild monkeys in the national park.', 'General'),
  ('b1_333', 'feel', 'v.', '/fiːl/', 'รู้สึก', 'You will feel proud and confident when you pass your B1 exam.', 'General'),
  ('b1_334', 'festival', 'n.', '/ˈfestɪvl/', 'เทศกาล', 'The annual lantern festival attracts tourists from all around the world.', 'Arts & Leisure'),
  ('b1_335', 'fetch', 'v.', '/fetʃ/', 'ไปเอามา, นำมา', 'The faithful golden retriever ran to fetch the rubber tennis ball.', 'General'),
  ('b1_336', 'fight', 'v.', '/faɪt/', 'ต่อสู้', 'Doctors and nurses fight tirelessly to protect community public health.', 'General'),
  ('b1_337', 'figure out', 'phr. v.', '/ˈfɪɡər aʊt/', 'คิดหาทางออกได้, แก้ปัญหาได้', 'It took our engineers three days to figure out the software bug.', 'Verbs & Expressions'),
  ('b1_338', 'fill', 'v.', '/fɪl/', 'เติมให้เต็ม', 'Fill the reusable water bottle before embarking on your mountain hike.', 'General'),
  ('b1_339', 'filter', 'v.', '/ˈfɪltər/', 'กรองข้อมูล/น้ำ', 'You can easily filter vocabulary cards by theme or learning status.', 'General'),
  ('b1_340', 'find out', 'phr. v.', '/faɪnd aʊt/', 'สืบรู้, ค้นพบความจริง', 'I was astonished to find out that she speaks five languages fluently.', 'Verbs & Expressions'),
  ('b1_341', 'fit', 'v.', '/fɪt/', 'พอดี, เหมาะสม', 'These comfortable walking shoes fit perfectly for long city walking tours.', 'General'),
  ('b1_342', 'fix', 'v.', '/fɪks/', 'ซ่อมแซม', 'The bicycle mechanic fixed the slipped chain in less than ten minutes.', 'General'),
  ('b1_343', 'flash', 'v.', '/flæʃ/', 'กะพริบแสง', 'Warning lights flashed at the railroad crossing as the train approached.', 'General'),
  ('b1_344', 'flavour', 'n.', '/ˈfleɪvər/', 'รสชาติ, กลิ่นรส', 'Add fresh basil and black pepper to enhance the natural flavour of the soup.', 'Health & Food'),
  ('b1_345', 'flexible', 'adj.', '/ˈfleksəbl/', 'ยืดหยุ่น, ปรับเปลี่ยนได้', 'Our employer offers flexible remote working hours for all developers.', 'Descriptive Words'),
  ('b1_346', 'float', 'v.', '/fləʊt/', 'ลอยน้ำ', 'Dry fallen leaves floated gently down the winding autumn river.', 'General'),
  ('b1_347', 'flood', 'n.', '/flʌd/', 'น้ำท่วม, อุทกภัย', 'Heavy monsoon rain triggered flash floods across the low-lying northern province.', 'Environment & Nature'),
  ('b1_348', 'fluent', 'adj.', '/ˈfluːənt/', 'พูดภาษาได้อย่างคล่องแคล่ว', 'After living in Madrid for two years, she became completely fluent in Spanish.', 'Media & Society'),
  ('b1_349', 'fly', 'v.', '/flaɪ/', 'บิน', 'Flocks of migratory birds fly south to warmer climates each October.', 'General'),
  ('b1_350', 'focus', 'v.', '/ˈfəʊkəs/', 'เพ่งความสนใจ', 'Focus on memorizing five new words every morning to build confidence.', 'General'),
  ('b1_351', 'fold', 'v.', '/fəʊld/', 'พับ', 'Fold your clean clothes neatly before packing them into your suitcase.', 'General'),
  ('b1_352', 'follow', 'v.', '/ˈfɒləʊ/', 'ติดตาม, ปฏิบัติตาม', 'Always follow safety instructions when visiting chemistry laboratories.', 'General'),
  ('b1_353', 'forbid', 'v.', '/fəˈbɪd/', 'สั่งห้ามเด็ดขาด', 'National park regulations strictly forbid littering and lighting campfires.', 'General'),
  ('b1_354', 'force', 'v.', '/fɔːs/', 'บังคับ', 'Nobody can force you to learn; genuine curiosity must come from within.', 'General'),
  ('b1_355', 'forecast', 'n.', '/ˈfɔːkɑːst/', 'พยากรณ์อากาศ', 'Check tomorrow''s weather forecast to decide whether to carry an umbrella.', 'Environment & Nature'),
  ('b1_356', 'forgive', 'v.', '/fəˈɡɪv/', 'ยกโทษให้, ให้อภัย', 'It took time, but she finally decided to forgive his honest mistake.', 'Daily Life'),
  ('b1_357', 'freeze', 'v.', '/friːz/', 'แช่แข็ง, กลายเป็นน้ำแข็ง', 'Ponds freeze solid during harsh northern winter months.', 'General'),
  ('b1_358', 'frequent', 'adj.', '/ˈfriːkwənt/', 'บ่อยครั้ง, ถี่', 'He is a frequent business traveler who flies between Singapore and Sydney.', 'Descriptive Words'),
  ('b1_359', 'friendship', 'n.', '/ˈfrendʃɪp/', 'มิตรภาพ', 'True friendship is built upon honesty, trust, and mutual respect.', 'Relationships'),
  ('b1_360', 'frighten', 'v.', '/ˈfraɪtn/', 'ทำให้ตกใจกลัว', 'Sudden loud thunderclaps can frighten small domestic animals.', 'General'),
  ('b1_361', 'frightened', 'adj.', '/ˈfraɪtnd/', 'ตกใจกลัว', 'The sudden crack of loud thunder frightened the small puppy.', 'Emotions & Traits'),
  ('b1_362', 'fulfil', 'v.', '/fʊlˈfɪl/', 'เติมเต็ม, บรรลุความฝัน', 'She fulfilled her lifelong ambition by earning a commercial pilot license.', 'General'),
  ('b1_363', 'furniture', 'n.', '/ˈfɜːnɪtʃər/', 'เฟอร์นิเจอร์, เครื่องเรือน', 'Solid oak furniture is renowned for its timeless beauty and durability.', 'Home & Living'),
  ('b1_364', 'gain', 'v.', '/ɡeɪn/', 'ได้รับเพิ่ม', 'Daily reading helps learners gain valuable exposure to natural grammar.', 'General'),
  ('b1_365', 'gallery', 'n.', '/ˈɡæləri/', 'หอศิลป์', 'Admission to the contemporary art gallery is free on Sunday mornings.', 'Arts & Leisure'),
  ('b1_366', 'garage', 'n.', '/ˈɡærɑːʒ/', 'โรงจอดรถ', 'Park the family vehicle safely inside the garage overnight.', 'Home & Living'),
  ('b1_367', 'gather', 'v.', '/ˈɡæðər/', 'รวบรวม, ชุมนุม', 'Friends gathered around the fireplace to share memorable travel stories.', 'General'),
  ('b1_368', 'gaze', 'v.', '/ɡeɪz/', 'จ้องมองอย่างเพลิดเพลิน', 'We gazed in awe at the starry night sky over the desert.', 'General'),
  ('b1_369', 'generate', 'v.', '/ˈdʒenəreɪt/', 'สร้างขึ้น, กำเนิด', 'Wind turbines generate clean renewable electricity for thousands of homes.', 'General'),
  ('b1_370', 'generation', 'n.', '/ˌdʒenəˈreɪʃn/', 'คนรุ่น, ยุคสมัย', 'Digital smartphones have shaped the communication habits of this generation.', 'Relationships'),
  ('b1_371', 'generous', 'adj.', '/ˈdʒenərəs/', 'ใจกว้าง, เอื้อเฟื้อเผื่อแผ่', 'The local philanthropist made a generous financial donation to the children''s hospital.', 'Emotions & Traits'),
  ('b1_372', 'genuine', 'adj.', '/ˈdʒenjuɪn/', 'แท้จริง, ไม่ปลอมแปลง', 'The antique specialist verified that the bronze coin was genuine.', 'Descriptive Words'),
  ('b1_373', 'give up', 'phr. v.', '/ɡɪv ʌp/', 'ยอมแพ้, เลิกทำ', 'Never give up on your dreams, even when facing difficult obstacles.', 'Verbs & Expressions'),
  ('b1_374', 'glance', 'v.', '/ɡlɑːns/', 'ชำเลืองมอง', 'He glanced at his wristwatch and realized he had ten minutes to spare.', 'General'),
  ('b1_375', 'global', 'adj.', '/ˈɡləʊbl/', 'ระดับโลก, ทั่วโลก', 'Deforestation is a pressing global problem that demands international cooperation.', 'Environment & Nature'),
  ('b1_376', 'govern', 'v.', '/ˈɡʌvn/', 'ปกครอง, ควบคุม', 'Ethical principles should govern the responsible development of technology.', 'General'),
  ('b1_377', 'grab', 'v.', '/ɡræb/', 'คว้า, ฉวยเอา', 'Grab your jacket and umbrella before heading out into the rainy evening.', 'General'),
  ('b1_378', 'gradual', 'adj.', '/ˈɡrædʒuəl/', 'ค่อยเป็นค่อยไป', 'Language acquisition is a gradual process requiring regular daily dedication.', 'Descriptive Words'),
  ('b1_379', 'graduate', 'v.', '/ˈɡrædʒueɪt/', 'สำเร็จการศึกษา', 'Most university students graduate after completing four years of study.', 'Education & Tech'),
  ('b1_380', 'grateful', 'adj.', '/ˈɡreɪtfl/', 'รู้สึกขอบคุณ, ซาบซึ้งใจ', 'I am deeply grateful for all the guidance and encouragement you provided.', 'Emotions & Traits'),
  ('b1_381', 'greet', 'v.', '/ɡriːt/', 'ทักทาย', 'The hotel concierge greeted international guests with a warm, welcoming smile.', 'General'),
  ('b1_382', 'grin', 'v.', '/ɡrɪn/', 'ยิ้มกว้าง', 'She grinned happily after discovering that she scored full marks on the quiz.', 'General'),
  ('b1_383', 'groom', 'n.', '/ɡruːm/', 'เจ้าบ่าว', 'The handsome groom waited patiently at the altar for his bride.', 'Relationships'),
  ('b1_384', 'grow up', 'phr. v.', '/ɡrəʊ ʌp/', 'เติบโตขึ้น', 'Children grow up surprisingly fast these days.', 'Verbs & Expressions'),
  ('b1_385', 'guarantee', 'n.', '/ˌɡærənˈtiː/', 'การรับประกันสินค้า', 'The digital camera comes with a two-year international manufacturer guarantee.', 'Shopping & City'),
  ('b1_386', 'guard', 'v.', '/ɡɑːd/', 'คุ้มกัน, เฝ้าดูแล', 'Trained security personnel guard the historic national museum around the clock.', 'General'),
  ('b1_387', 'guess', 'v.', '/ɡes/', 'คาดเดา', 'Try to guess the word''s meaning from context clues before checking a dictionary.', 'General'),
  ('b1_388', 'guide', 'v.', '/ɡaɪd/', 'นำทาง, ชี้แนะ', 'The experienced mountain ranger guided hikers safely across the rocky ridge.', 'General'),
  ('b1_389', 'handle', 'v.', '/ˈhændl/', 'จัดการ, หยิบจับ', 'Please handle the antique ceramic vase with extreme caution.', 'General'),
  ('b1_390', 'hang', 'v.', '/hæŋ/', 'แขวน', 'Hang your winter coats on the rack beside the front entrance.', 'General'),
  ('b1_391', 'happen', 'v.', '/ˈhæpən/', 'เกิดขึ้น', 'Unexpected adventures often happen when you travel off the beaten track.', 'General'),
  ('b1_392', 'hardware', 'n.', '/ˈhɑːdweər/', 'ฮาร์ดแวร์, ชิ้นส่วนอุปกรณ์', 'The computer technician upgraded our server hardware yesterday.', 'Education & Tech'),
  ('b1_393', 'harm', 'v.', '/hɑːm/', 'ทำอันตราย', 'Pollution from untreated factory waste can harm delicate freshwater ecosystems.', 'General'),
  ('b1_394', 'harmless', 'adj.', '/ˈhɑːmləs/', 'ไม่มีพิษมีภัย, ปลอดภัย', 'Most common house spiders are completely harmless to humans.', 'Descriptive Words'),
  ('b1_395', 'harvest', 'v.', '/ˈhɑːvɪst/', 'เก็บเกี่ยวพืชผล', 'Farmers harvest golden wheat fields before the autumn rains arrive.', 'General'),
  ('b1_396', 'hate', 'v.', '/heɪt/', 'เกลียด', 'Most commuters hate being delayed in bumper-to-bumper traffic jams.', 'General'),
  ('b1_397', 'headline', 'n.', '/ˈhedlaɪn/', 'พาดหัวข่าว', 'The dramatic news headline immediately caught everyone''s attention this morning.', 'Media & Society'),
  ('b1_398', 'heal', 'v.', '/hiːl/', 'เยียวยา, สมานแผล', 'The minor knee scratch will heal completely within a few days.', 'General'),
  ('b1_399', 'healthy', 'adj.', '/ˈhelθi/', 'มีสุขภาพดี', 'Eating fresh fruit daily is a simple way to maintain a healthy lifestyle.', 'Health & Food'),
  ('b1_400', 'heat', 'v.', '/hiːt/', 'อุ่นให้ร้อน', 'Gently heat the leftover vegetable soup in a small saucepan.', 'General'),
  ('b1_401', 'heating', 'n.', '/ˈhiːtɪŋ/', 'ระบบทำความร้อน', 'The central heating automatically turns on when the temperature drops.', 'Home & Living'),
  ('b1_402', 'hesitant', 'adj.', '/ˈhezɪtənt/', 'ลังเลใจ, ไม่แน่ใจ', 'She felt hesitant to invest in the newly founded venture company.', 'Descriptive Words'),
  ('b1_403', 'hesitate', 'v.', '/ˈhezɪteɪt/', 'ลังเลใจ', 'Do not hesitate to reach out if you need additional assistance.', 'Daily Life'),
  ('b1_404', 'hide', 'v.', '/haɪd/', 'ซ่อนตัว', 'The timid deer hid behind tall pine trees as hikers walked by.', 'General'),
  ('b1_405', 'hilarious', 'adj.', '/hɪˈleəriəs/', 'ตลกขบขันอย่างยิ่ง', 'The comedian''s stand-up routine was hilarious from start to finish.', 'Descriptive Words'),
  ('b1_406', 'hire', 'v.', '/ˈhaɪər/', 'เช่า, ว่าจ้าง', 'We decided to hire bicycles to explore the scenic canals of Amsterdam.', 'General'),
  ('b1_407', 'hit', 'v.', '/hɪt/', 'ตี, ชน', 'The tennis champion hit a powerful baseline ace down the line.', 'General'),
  ('b1_408', 'hold', 'v.', '/həʊld/', 'ถือไว้, จัดงาน', 'The university will hold its annual science symposium in the main hall.', 'General'),
  ('b1_409', 'honour', 'v.', '/ˈɒnər/', 'ให้เกียรติ, เชิดชู', 'The community ceremony honored courageous emergency rescue workers.', 'General'),
  ('b1_410', 'hope', 'v.', '/həʊp/', 'หวังว่า', 'We hope you enjoy using this modern mobile-first vocabulary application!', 'General'),
  ('b1_411', 'hug', 'v.', '/hʌɡ/', 'สวมกอด', 'Family members hugged warmly at the airport arrivals terminal gate.', 'General'),
  ('b1_412', 'hunt', 'v.', '/hʌnt/', 'ล่า, ค้นหา', 'Bargain hunters search antique flea markets for rare vintage collectibles.', 'General'),
  ('b1_413', 'hurricane', 'n.', '/ˈhʌrɪkən/', 'พายุเฮอริเคน', 'Residents boarded up their windows ahead of the category 4 hurricane.', 'Environment & Nature'),
  ('b1_414', 'hurry', 'v.', '/ˈhʌri/', 'รีบเร่ง', 'We had to hurry along the platform so we would not miss the last train.', 'General'),
  ('b1_415', 'hurt', 'v.', '/hɜːt/', 'เจ็บปวด, ทำร้าย', 'Wearing improper running shoes can hurt your knees during road marathons.', 'General'),
  ('b1_416', 'identify', 'v.', '/aɪˈdentɪfaɪ/', 'ระบุตัวตน, ชี้ตัว', 'Botanists can easily identify plant species from leaf vein patterns.', 'General'),
  ('b1_417', 'ignore', 'v.', '/ɪɡˈnɔːr/', 'เพิกเฉย, ละเลย', 'Never ignore dashboard warning lights while driving long distances.', 'General'),
  ('b1_418', 'illustrate', 'v.', '/ˈɪləstreɪt/', 'วาดภาพประกอบ, อธิบาย', 'The lecturer used clear diagrams to illustrate the human circulatory system.', 'General'),
  ('b1_419', 'imagine', 'v.', '/ɪˈmædʒɪn/', 'จินตนาการ, นึกภาพ', 'It is hard to imagine modern daily life without smartphones.', 'Daily Life'),
  ('b1_420', 'imitate', 'v.', '/ˈɪmɪteɪt/', 'เลียนแบบ', 'Young children naturally imitate speech patterns of the people around them.', 'General'),
  ('b1_421', 'imply', 'v.', '/ɪmˈplaɪ/', 'บอกเป็นนัย', 'His subtle smile seemed to imply that the surprise had succeeded.', 'General'),
  ('b1_422', 'import', 'v.', '/ɪmˈpɔːt/', 'นำเข้าสินค้า', 'The country imports seasonal fresh fruits from Mediterranean orchards.', 'General'),
  ('b1_423', 'impress', 'v.', '/ɪmˈpres/', 'สร้างความประทับใจ', 'Her articulate presentation impressed the entire panel of interviewers.', 'General'),
  ('b1_424', 'impressive', 'adj.', '/ɪmˈpresɪv/', 'น่าประทับใจอย่างยิ่ง', 'The new bridge across the bay is an impressive feat of civil engineering.', 'Descriptive Words'),
  ('b1_425', 'improve', 'v.', '/ɪmˈpruːv/', 'พัฒนา, ปรับปรุงให้ดีขึ้น', 'Daily practice will drastically improve your English fluency.', 'Daily Life'),
  ('b1_426', 'include', 'v.', '/ɪnˈkluːd/', 'รวมอยู่ด้วย', 'The Cambridge PET B1 exam includes reading, writing, listening, and speaking.', 'General'),
  ('b1_427', 'increase', 'v.', '/ɪnˈkriːs/', 'เพิ่มขึ้น', 'Regular aerobic exercise increases lung capacity and physical stamina.', 'General'),
  ('b1_428', 'incredible', 'adj.', '/ɪnˈkredəbl/', 'เหลือเชื่อ, ยอดเยี่ยมมาก', 'The view from the mountain summit at sunrise was truly incredible.', 'Descriptive Words'),
  ('b1_429', 'indicate', 'v.', '/ˈɪndɪkeɪt/', 'บ่งชี้', 'Recent survey statistics indicate growing interest in green lifestyle habits.', 'General'),
  ('b1_430', 'inevitable', 'adj.', '/ɪnˈevɪtəbl/', 'หลีกเลี่ยงไม่ได้', 'With rapid technological progress, automation was inevitable across many sectors.', 'Descriptive Words'),
  ('b1_431', 'inform', 'v.', '/ɪnˈfɔːm/', 'แจ้งให้ทราบ', 'The airline will inform passengers promptly of any schedule revisions.', 'General'),
  ('b1_432', 'ingredient', 'n.', '/ɪnˈɡriːdiənt/', 'ส่วนผสมอาหาร', 'Olive oil, garlic, and ripe tomatoes are the core ingredients of this recipe.', 'Health & Food'),
  ('b1_433', 'injure', 'v.', '/ˈɪndʒər/', 'ทำให้บาดเจ็บ', 'Be careful not to injure your lower back when lifting heavy parcels.', 'General'),
  ('b1_434', 'injury', 'n.', '/ˈɪndʒəri/', 'การบาดเจ็บ', 'The football star took six weeks to recover from a minor knee injury.', 'Health & Food'),
  ('b1_435', 'innocent', 'adj.', '/ˈɪnəsnt/', 'บริสุทธิ์, ไร้เดียงสา', 'The jury found the defendant completely innocent of all charges.', 'Descriptive Words'),
  ('b1_436', 'insist', 'v.', '/ɪnˈsɪst/', 'ยืนกราน', 'Our generous host insisted on paying for our celebration dinner.', 'General'),
  ('b1_437', 'inspect', 'v.', '/ɪnˈspekt/', 'ตรวจสอบ', 'Safety marshals inspect all carnival rides before the fair opens.', 'General'),
  ('b1_438', 'inspire', 'v.', '/ɪnˈspaɪər/', 'สร้างแรงบันดาลใจ', 'The marathon runner''s remarkable recovery inspired athletes across the nation.', 'General'),
  ('b1_439', 'install', 'v.', '/ɪnˈstɔːl/', 'ติดตั้งโปรแกรม', 'Click the install button to set up the interactive flashcard app.', 'Education & Tech'),
  ('b1_440', 'instruct', 'v.', '/ɪnˈstrʌkt/', 'สั่งสอน, แนะนำวิธี', 'The fitness trainer instructed clients on proper barbell posture.', 'General'),
  ('b1_441', 'instrument', 'n.', '/ˈɪnstrəmənt/', 'เครื่องดนตรี', 'Playing a musical instrument like the violin enhances cognitive skills.', 'Arts & Leisure'),
  ('b1_442', 'insult', 'v.', '/ɪnˈsʌlt/', 'ดูถูก, สบประมาท', 'Polite individuals never insult someone over differing opinions.', 'General'),
  ('b1_443', 'intend', 'v.', '/ɪnˈtend/', 'ตั้งใจ, มุ่งหมาย', 'I intend to complete the Cambridge preparation course by next month.', 'Daily Life'),
  ('b1_444', 'interfere', 'v.', '/ˌɪntəˈfɪər/', 'แทรกแซง', 'Do not let background distractions interfere with your study schedule.', 'General'),
  ('b1_445', 'interpret', 'v.', '/ɪnˈtɜːprɪt/', 'แปลความหมาย', 'Art historians interpret the symbolic meanings hidden within Renaissance paintings.', 'General'),
  ('b1_446', 'interrupt', 'v.', '/ˌɪntəˈrʌpt/', 'ขัดจังหวะ', 'Please let him finish speaking before you interrupt.', 'Daily Life'),
  ('b1_447', 'interview', 'n.', '/ˈɪntəvjuː/', 'การสัมภาษณ์งาน', 'Dress professionally and arrive ten minutes early for your job interview.', 'Work & Career'),
  ('b1_448', 'introduce', 'v.', '/ˌɪntrəˈdjuːs/', 'แนะนำให้รู้จัก', 'Allow me to introduce our visiting international language instructor.', 'General'),
  ('b1_449', 'invent', 'v.', '/ɪnˈvent/', 'ประดิษฐ์คิดค้น', 'Alexander Graham Bell invented the telephone in the nineteenth century.', 'General'),
  ('b1_450', 'invest', 'v.', '/ɪnˈvest/', 'ลงทุน', 'Investing time in your English language skills opens global career doors.', 'General'),
  ('b1_451', 'investigate', 'v.', '/ɪnˈvestɪɡeɪt/', 'สืบสวน', 'Detectives investigated the cause of the sudden warehouse fire.', 'General'),
  ('b1_452', 'invite', 'v.', '/ɪnˈvaɪt/', 'เชิญชวน', 'They invited fifty close friends to celebrate their wedding anniversary.', 'General'),
  ('b1_453', 'involve', 'v.', '/ɪnˈvɒlv/', 'เกี่ยวข้อง, เกี่ยวพัน', 'Preparing for international exams involves dedication, practice, and review.', 'General'),
  ('b1_454', 'iron', 'v.', '/ˈaɪən/', 'รีดผ้า', 'Iron your shirt neatly before attending formal corporate interviews.', 'General'),
  ('b1_455', 'irritate', 'v.', '/ˈɪrɪteɪt/', 'ทำให้ระคายเคือง/หงุดหงิด', 'Blinking frequently soothes dry eyes irritated by computer screens.', 'General'),
  ('b1_456', 'isolate', 'v.', '/ˈaɪsəleɪt/', 'แยกตัวออกไป', 'Quarantine protocols isolate infectious patients to safeguard others.', 'General'),
  ('b1_457', 'itinerary', 'n.', '/aɪˈtɪnərəri/', 'กำหนดการเดินทาง, แผนการเที่ยว', 'Our seven-day Europe itinerary covers Paris, Brussels, and Amsterdam.', 'Travel & Transport'),
  ('b1_458', 'jealous', 'adj.', '/ˈdʒeləs/', 'อิจฉา, หึงหวง', 'Try not to feel jealous of other people''s fast achievements; focus on your own growth.', 'Emotions & Traits'),
  ('b1_459', 'jog', 'v.', '/dʒɒɡ/', 'วิ่งเหยาะๆ', 'Jogging around the park at sunrise is a refreshing morning routine.', 'General'),
  ('b1_460', 'join', 'v.', '/dʒɔɪn/', 'เข้าร่วม', 'Join our online study group to practice conversational English daily.', 'General'),
  ('b1_461', 'journalist', 'n.', '/ˈdʒɜːnəlɪst/', 'นักข่าว, ผู้สื่อข่าว', 'Investigative journalists uncovered vital evidence regarding environmental pollution.', 'Media & Society'),
  ('b1_462', 'journey', 'n.', '/ˈdʒɜːni/', 'การเดินทางระยะทางไกล', 'The train journey through the Swiss Alps offers breathtaking alpine scenery.', 'Travel & Transport'),
  ('b1_463', 'judge', 'v.', '/dʒʌdʒ/', 'ตัดสิน', 'Do not judge a book by its cover; explore its contents first.', 'General'),
  ('b1_464', 'jump', 'v.', '/dʒʌmp/', 'กระโดด', 'The excited children jumped into the swimming pool on a hot afternoon.', 'General'),
  ('b1_465', 'justify', 'v.', '/ˈdʒʌstɪfaɪ/', 'ให้เหตุผลสนับสนุน', 'Can you justify your decision to prioritize vocabulary acquisition first?', 'General'),
  ('b1_466', 'keep', 'v.', '/kiːp/', 'เก็บรักษา, ทำอย่างต่อเนื่อง', 'Keep your study streak burning bright by reviewing ten words daily.', 'General'),
  ('b1_467', 'keep up with', 'phr. v.', '/kiːp ʌp wɪð/', 'ตามให้ทัน', 'It can be challenging to keep up with the latest technological developments.', 'Verbs & Expressions'),
  ('b1_468', 'kick', 'v.', '/kɪk/', 'เตะ', 'The midfielder kicked a precise pass directly to the advancing striker.', 'General'),
  ('b1_469', 'kiss', 'v.', '/kɪs/', 'จูบ', 'Parents kissed their children goodnight before turning off bedroom lights.', 'General'),
  ('b1_470', 'kitchen', 'n.', '/ˈkɪtʃɪn/', 'ห้องครัว', 'The aroma of freshly baked garlic bread filled the entire kitchen.', 'Home & Living'),
  ('b1_471', 'kneel', 'v.', '/niːl/', 'คุกเข่า', 'Gardeners kneel on padded mats while weeding delicate flower beds.', 'General'),
  ('b1_472', 'knit', 'v.', '/nɪt/', 'ถักไหมพรม', 'Grandmother knitted a warm woollen scarf for the cold winter weather.', 'General'),
  ('b1_473', 'knock', 'v.', '/nɒk/', 'เคาะประตู', 'Always knock politely on closed office doors before entering.', 'General'),
  ('b1_474', 'label', 'v.', '/ˈleɪbl/', 'ติดป้ายฉลาก', 'Label all your travel luggage bags clearly with your phone number.', 'General'),
  ('b1_475', 'laboratory', 'n.', '/ləˈbɒrətri/', 'ห้องปฏิบัติการ, ห้องแล็บ', 'Students must wear protective goggles when conducting chemistry experiments in the laboratory.', 'Education & Tech'),
  ('b1_476', 'lack', 'v.', '/læk/', 'ขาดแคลน', 'Plants will wither if they lack sufficient sunlight and clean water.', 'General'),
  ('b1_477', 'land', 'v.', '/lænd/', 'ลงจอด', 'The Airbus commercial aircraft landed smoothly despite strong coastal crosswinds.', 'General'),
  ('b1_478', 'last', 'v.', '/lɑːst/', 'คงอยู่, มีอายุการใช้งาน', 'These durable leather boots will last for many years of hiking.', 'General'),
  ('b1_479', 'laugh', 'v.', '/lɑːf/', 'หัวเราะ', 'Everyone laughed heartily at the comedian''s clever observational jokes.', 'General'),
  ('b1_480', 'launch', 'v.', '/lɔːntʃ/', 'เปิดตัว, ยิงจรวด', 'The tech startup launched its revolutionary mobile app on Vercel.', 'General'),
  ('b1_481', 'lead', 'v.', '/liːd/', 'นำทาง, เป็นผู้นำ', 'Experienced guides lead travelers through breathtaking alpine trails.', 'General'),
  ('b1_482', 'leak', 'v.', '/liːk/', 'รั่วไหล', 'The kitchen water pipe began to leak under the sink basin.', 'General'),
  ('b1_483', 'lean', 'v.', '/liːn/', 'พิง, เอนตัว', 'Do not lean against the subway doors while the train is in motion.', 'General'),
  ('b1_484', 'leap', 'v.', '/liːp/', 'กระโดดข้าม', 'The athletic gazelle leaped gracefully over the wooden pasture fence.', 'General'),
  ('b1_485', 'learn', 'v.', '/lɜːn/', 'เรียนรู้', 'Learn vocabulary through contextual sentences rather than isolated word lists.', 'General'),
  ('b1_486', 'leave', 'v.', '/liːv/', 'ออกจาก, ทิ้งไว้', 'Remember to leave your hotel room keycard at the front reception.', 'General'),
  ('b1_487', 'lecture', 'n.', '/ˈlektʃər/', 'การบรรยายในห้องเรียน', 'The visiting professor gave an inspiring guest lecture on artificial intelligence.', 'Education & Tech'),
  ('b1_488', 'leisure', 'n.', '/ˈleʒər/', 'เวลาว่าง, กิจกรรมยามว่าง', 'What sports do you enjoy participating in during your leisure time?', 'Arts & Leisure'),
  ('b1_489', 'lend', 'v.', '/lend/', 'ให้ยืม', 'Could you lend me an umbrella until the afternoon storm clears?', 'General'),
  ('b1_490', 'let', 'v.', '/let/', 'อนุญาตให้', 'Let curiosity be your greatest teacher on your language journey.', 'General'),
  ('b1_491', 'library', 'n.', '/ˈlaɪbrəri/', 'ห้องสมุด', 'You can borrow up to six academic textbooks from the campus library.', 'Education & Tech'),
  ('b1_492', 'lift', 'v.', '/lɪft/', 'ยกขึ้น', 'Ask for assistance when you need to lift heavy airport baggage.', 'General'),
  ('b1_493', 'light', 'v.', '/laɪt/', 'จุดไฟ, ส่องสว่าง', 'They lit scented candles around the dining table for the celebration.', 'General'),
  ('b1_494', 'lightning', 'n.', '/ˈlaɪtnɪŋ/', 'ฟ้าแลบ, ฟ้าผ่า', 'Brilliant flashes of lightning lit up the stormy midnight sky.', 'Environment & Nature'),
  ('b1_495', 'limit', 'v.', '/ˈlɪmɪt/', 'จำกัดขอบเขต', 'Limit your daily screen time before sleep to improve deep rest.', 'General'),
  ('b1_496', 'link', 'v.', '/lɪŋk/', 'เชื่อมโยง', 'The online platform links learners with native conversation partners worldwide.', 'General'),
  ('b1_497', 'listen', 'v.', '/ˈlɪsn/', 'รับฟังอย่างตั้งใจ', 'Listen carefully to the authentic pronunciation to train your accent.', 'General'),
  ('b1_498', 'live', 'v.', '/lɪv/', 'อาศัยอยู่', 'Many international university students live in shared city flats.', 'General'),
  ('b1_499', 'load', 'v.', '/ləʊd/', 'บรรทุก, โหลดข้อมูล', 'The web application loads in milliseconds thanks to modern Vite bundling.', 'General'),
  ('b1_500', 'locate', 'v.', '/ləʊˈkeɪt/', 'หาตำแหน่ง, ตั้งอยู่', 'GPS navigation systems help drivers locate remote countryside addresses.', 'General')
ON CONFLICT (id) DO UPDATE SET
  word = EXCLUDED.word,
  pos = EXCLUDED.pos,
  ipa = EXCLUDED.ipa,
  meaning = EXCLUDED.meaning,
  example = EXCLUDED.example,
  category = EXCLUDED.category;
